In [9]:
import numpy as np

In [10]:
np.__version__

'2.3.1'

In [11]:
# list , array
lst =[1,2,3,4,5,6]
arr=np.array(lst)

In [4]:
arr

array([1, 2, 3, 4, 5, 6])

In [12]:
arr=np.array([1,2,3,4,5,6,7])

In [10]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [11]:
lst=[1,2,3,4,5,6,7]
print("type of list ",type(lst))
arr =np.array(lst)
print(arr)
print("type of array: ",type(arr))

type of list  <class 'list'>
[1 2 3 4 5 6 7]
type of array:  <class 'numpy.ndarray'>


In [13]:
arr= np.array(list(range(1,21)))
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [14]:
arr =np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((5,10)) # 5 rows 10 column

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
np.ones((5,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [15]:
arr= np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [17]:
arr= np.arange(0,30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [20]:
arr.reshape(5,6)


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [21]:
arr= np.random.randint(1,5,(3,3))
arr

array([[1, 3, 2],
       [3, 2, 3],
       [2, 4, 2]], dtype=int32)

In [22]:
arr= np.random.random(10)
arr

array([0.88177862, 0.06469633, 0.78200033, 0.36288056, 0.892663  ,
       0.12248709, 0.31343223, 0.73534666, 0.07690496, 0.35923212])

In [24]:
arr= np.random.random((5,10))
arr

array([[0.59953739, 0.7876898 , 0.7438967 , 0.49933469, 0.82283335,
        0.80106323, 0.15349397, 0.04613157, 0.72045465, 0.53659518],
       [0.632669  , 0.23725556, 0.14423767, 0.94744169, 0.29335553,
        0.34147665, 0.10681309, 0.72676683, 0.89564811, 0.47994369],
       [0.13737574, 0.67837089, 0.11438515, 0.78296989, 0.41690745,
        0.7403451 , 0.49322975, 0.25125278, 0.71120939, 0.06542976],
       [0.73835798, 0.40408308, 0.34161934, 0.7034343 , 0.40699094,
        0.51705729, 0.98755916, 0.76053015, 0.31282655, 0.29880387],
       [0.40643912, 0.66750566, 0.98519432, 0.82154725, 0.66346297,
        0.48278614, 0.77810113, 0.8547185 , 0.08859803, 0.29675591]])

In [25]:
arr=np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [27]:
print("shape of array:- ",arr.shape)
print("size of array:- ", arr.size)
print("data types:- ",arr.dtype)
print("number of dimension ",arr.ndim)


shape of array:-  (12, 5)
size of array:-  60
data types:-  int64
number of dimension  2


In [28]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [29]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [30]:
arr.shape

(12, 5)

In [32]:
arr.T.shape

(5, 12)

In [35]:
arr =np.arange(30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [36]:
arr[0:12]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [38]:
arr[0]=100

In [39]:
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [42]:
arr=np.arange(60).reshape(12,5)


In [44]:
arr[1,3:5]

array([8, 9])

In [41]:
arr[1,1]

np.int64(6)

In [45]:
arr[0:5,1:2]

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [47]:
arr[1,1]=100

In [48]:
arr

array([[  0,   1,   2,   3,   4],
       [  5, 100,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [49]:
arr[11,4]

np.int64(59)

In [50]:
arr[-1][-1]

np.int64(59)

In [51]:
arr[11][-1]

np.int64(59)

In [52]:
arr[-1,-1]

np.int64(59)

In [54]:
arr =np.array(np.arange(225).reshape(5,15,3))

In [56]:
arr.ndim, arr.shape ,arr.size, arr.dtype

(3, (5, 15, 3), 225, dtype('int64'))

In [57]:
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [58]:
arr[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [59]:
arr[2]

array([[ 90,  91,  92],
       [ 93,  94,  95],
       [ 96,  97,  98],
       [ 99, 100, 101],
       [102, 103, 104],
       [105, 106, 107],
       [108, 109, 110],
       [111, 112, 113],
       [114, 115, 116],
       [117, 118, 119],
       [120, 121, 122],
       [123, 124, 125],
       [126, 127, 128],
       [129, 130, 131],
       [132, 133, 134]])

In [61]:
arr[0,2:,2]

array([ 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44])

In [62]:
arr[0, 3:5]

array([[ 9, 10, 11],
       [12, 13, 14]])

In [64]:
arr[:,0,:]

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137],
       [180, 181, 182]])

In [67]:
arr[:,0:1,0:1]

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [71]:
arr[0,1,1]=100


In [72]:
arr[0,1,1]

np.int64(100)

In [73]:
arr=np.array([1,5,3,5,6,3])

In [74]:
arr.sort()

In [75]:
arr

array([1, 3, 3, 5, 5, 6])

In [77]:
arr+2

array([3, 5, 5, 7, 7, 8])

In [78]:
arr-2

array([-1,  1,  1,  3,  3,  4])

In [79]:
arr*2

array([ 2,  6,  6, 10, 10, 12])

In [80]:
arr/2

array([0.5, 1.5, 1.5, 2.5, 2.5, 3. ])

In [81]:
arr1=np.array((1,2,3,4,6,))
arr2=np.array((1,2,8,5,9,))

In [82]:
arr1+arr2

array([ 2,  4, 11,  9, 15])

In [84]:
arr1*arr2

array([ 1,  4, 24, 20, 54])

In [85]:
arr1-arr2

array([ 0,  0, -5, -1, -3])